# Install dependencies only when needed
FROM node:16-alpine
WORKDIR /usr/src/app

RUN apk add --no-cache libc6-compat

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* ./
RUN yarn
RUN yarn build

COPY . .