version: "3"

services:
  meltrip-front:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/app/node_modules
  apache:
    image: httpd:latest
    container_name: apache-app
    ports:
      - "8080:80"
    volumes:
      - ./out:/usr/local/apache2/htdocs
